apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-app
  template:
    metadata:
      labels:
        app: iris-app
    spec:
      containers:
      - name: iris-container
        image: gcr.io/formidable-bus-465107-j2/iris-fastapi-app
        ports:
        - containerPort: 8000

