apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-log-ml-service
  labels:
    app: demo-log-ml-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-log-ml-service
  template:
    metadata:
      labels:
        app: demo-log-ml-service
    spec:
      serviceAccountName: telemetry-access  # Replace with existing SA or remove if not using
      containers:
      - name: fastapi-container
        image: us-central1-docker.pkg.dev/formidable-bus-465107-j2/my-repo/iris-pipeline:latest
        ports:
        - containerPort: 8200
        readinessProbe:
          httpGet:
            path: /ready_check
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live_check
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

