apiVersion: v1
kind: Service
metadata:
  name: demo-log-ml-service
  labels:
    app: demo-log-ml-service
spec:
  type: LoadBalancer
  selector:
    app: demo-log-ml-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

