name: CML CI/CD Pipeline

on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: formidable-bus-465107-j2
      CLUSTER: iris-cluster
      REGION: us-central1
      IMAGE_NAME: iris-fastapi-app

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: formidable-bus-465107-j2
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with base64-encoded JSON key
      run: |
        echo '${{ env.GCP_SA_JSON }}' > ${HOME}/gcloud-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
        gcloud config set project $PROJECT_ID

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME .

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME

    - name: Connect to GKE
      run: |
        gcloud container clusters get-credentials $CLUSTER --region $REGION

    - name: Replace project ID in deployment YAML
      run: |
        sed -i "s|gcr.io/.*/iris-fastapi-app|gcr.io/$PROJECT_ID/$IMAGE_NAME|g" deployment.yaml

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

